### ISSUE TITLE
Keyboard shortcut for inserting result link

### ISSUE THREAD

**Issue by dedrop** [antonmedv/numbr#15]
It'd be super useful if I could insert a link to a previous result (not assigned to a variable) with just the keyboard, without having to use the mouse. For instance, maybe by holding Alt while using Up/Down to go to the result, then releasing Alt to insert the link.

**Comment by antonmedv** [comment]
Nice idea 👍🏻

**Comment by antonmedv** [comment]
Currently Alt+Enter will put current line reference on the next line. 

Maybe Alt+something is a good idea.

**Comment by dedrop** [comment]
Hi, Anton. Just saw that both alt+enter and pasting after clicking a result are inserting references. It's great, thank you so much!

If I could suggest one more optimization, can you leave the keyboard focus where it is when clicking a result to copy? Right now, clicking a result removes the keyboard focus entirely. So if I'm mid-expression and click to copy, I have to mouse back then click the right place in the expression before pasting and continuing. If the focus stayed, I could just click then hit ctrl-v and keep typing. Don't know if that's possible...

Anyway, just a thought for a smoother experience. But it's already fantastic to have nameless references back!

Pedro
________________________________

**Comment by antonmedv** [comment]
Nice idea! Done!

**Comment by dedrop** [comment]
Awesome, thank you!

Pedro
________________________________
