### ISSUE TITLE
Share Document Link Goes to Old Version

### ISSUE THREAD

**Issue by dedrop** [antonmedv/numbr#16]
If I share a pretty URL from the "Share document" option then make more changes to the doc, the link goes to the doc without the subsequent changes. Ideally, the link would go to the latest version of the doc.

If that's difficult, my specific scenario isn't actually sharing but just needing a stable link to an ongoing scratchpad. Perhaps that could be handled more easily by some way to store a doc's ongoing content in web storage?

**Comment by antonmedv** [comment]
Sharing stuff properly is a little bit more work (+ server and storage). 

I'm looking to a way to somehow refactor it, without the need for the server on my side.

**Comment by dedrop** [comment]
Totally get it. I also think it's a lower priority. The much more valuable thing for me, at least, would be a scratchpad I can keep returning to with the same URL. Then I can favorite that scratchpad as a shortcut, in my Edge bar, as an icon on my desktop, etc. While a shareable stable URL would address this, so would other likely much easier solutions. A few examples, if you'll forgive the presumption:

1. Dead simplest could be to just store the last doc URL as I edit in web storage (at the same time as you're updating it due to the edits), then make https://numbr.dev/#last check that value and redirect there. Not great, since if I start a new doc I lose the ability to get back to the old one. But no worse than today, and works if I mostly just use one doc.
2. Perhaps a single special https://numbr.dev/#local or #scratch doc that stores its content in web storage.
3. Extending #2, allow saving docs locally by naming them, then accessing them with https://numbr.dev/local/docname or somesuch; their content again kept in web storage. This eventually leads to complications such as management, but probably still simpler than server storage and sharing.

Hope that makes sense. If this would be better as a new separate ticket, please just let me know and I'll take care of it. Thanks again for the great app!

**Comment by antonmedv** [comment]
I already tried something like this: https://numbr.dev/#draft

**Comment by dedrop** [comment]
Fantastic! Works exactly as I'd hoped. Must have missed that in the documentation. Thank you!

**Comment by antonmedv** [comment]
Going to make this as default behavior of the main page.

**Comment by chilikasha** [comment]
are there any options/workarounds to keep a fresh copy on multiple devices?

**Comment by antonmedv** [comment]
Right now nothing is stored on the server. No synchronisation. 

I need to implement server with auth/registration to implement this.
