### ISSUE TITLE
Can't close keyboard on iOS in Chrome

### ISSUE THREAD

**Issue by chilikasha** [antonmedv/numbr#8]
Hi,

Could you please check the video, can't close the keyboard on iOS in Chrome. Though works in Firefox, for example.
Thank you!
https://user-images.githubusercontent.com/3147449/182014109-f12fbac5-598b-4a99-a7da-209316db5470.MP4

**Comment by antonmedv** [comment]
In safari also works.

**Comment by chilikasha** [comment]
btw as a workaround you can hide it by tapping the right pane (where the
result is)

Вс, 31 июля 2022 г. в 09:18, Anton Medvedev ***@***.***>:
